title: 'Programming Tutorials/Challenges'
logo: logo.svg
email: andrewmthomas87@gmail.com
description: >
  Programming tutorials and challenges in Java and Javascript
url: 'http://andrewthomas.us'
baseurl: '/Tutorials'
github_username:  andrewthomas87

markdown: kramdown
