title: Programming
email: andrewmthomas87@gmail.com
description: >
  Programming tutorials and challenges
baseurl: '/Tutorials'
url: 'http://andrewthomas.us'
github_username: andrewmthomas87

markdown: redcarpet
markdown_ext: markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ['tables', 'autolink', 'strikethrough', 'space_after_headers', 'fenced_code_blocks']
