title: Programming Tutorials/Challenges
email: andrewmthomas87@gmail.com
description: >
  Test description
baseurl: '/Tutorials/'
url: 'http://andrewthomas.us'
github_username:  andrewmthomas87

markdown: kramdown
